name: Release

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: run-tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
  release:
    needs: tagpr
    if: needs.tagpr.outputs.tagpr-tag != ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pushover:
    name: pushover if failure
    needs: [release]
    if: failure()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: pushover-actions
      uses: umahmood/pushover-actions@v1.1.0
      env:
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API_KEY }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
      with:
        status: ${{ job.status }}
        title: "Failed ${{ github.event.repository.full_name }}'s workflow (${{ github.workflow }})"
        url: "${{ github.server_url }}/${{ github.event.repository.full_name }}/actions/runs/${{ github.run_id }}"
        priority: 1 # High
